---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-whale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-whale-app
      version: blue
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
      - name: hello-whale-container
        image: vamsijakkula/hellowhale:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-svc
  labels:
    app: hello-whale-app
spec:
  selector:
    app: hello-whale-app
    version: blue
  type: ClusterIP
  ports:
  #- nodePort: 31113
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-blue-whale
    http:
      paths:
      - path: /
        #pathType: Prefix
        backend:
          serviceName: hello-whale-svc
          servicePort: 80


