---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-whale
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: hello-blue-whale
      version: blue
  template:
    metadata:
      name: hello-blue-whale
      labels:
        app: hello-blue-whale
        version: blue    
    spec:
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: Labels
      #          operator: In
      #          values:
      #          - kubernetes.io/hostname=n0d3-2
      nodeSelector:
        kubernetes.io/hostname: n0d3-2
      containers:
      - name: hello-whale-container
        #image: vamsijakkula/hellowhale:latest
        image: josecarlosjr/hellowhale:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "100Mi"
          limits:  
            memory: "200Mi"
            cpu: "200m"
            ephemeral-storage: "250Mi"        
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - name: ssl
            mountPath: /etc/nginx/client/
      volumes:
        - name: ssl
          secret:
            secretName: proxy-ca-secret
---
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-svc
  labels:
    app: hello-blue-whale
    service: hello-blue-whale
spec:
  selector:
    app: hello-blue-whale
    version: blue
  type: ClusterIP
  #type: NodePort
  ports:
  #- nodePort: 31113
    #port exposta internamente no cluster porta do POD
  - port: 80
    #targetPort == servicePort acessado no browser
    targetPort: 80 
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https    
  selector:
    app: hello-blue-whale
---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: hello-whale-ingress
#  annotations:  
#    nginx.ingress.kubernetes.io/rewrite-target: /  
#    kubernetes.io/ingress.class: nginx
#    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
#    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#  #labels:
#  #  app: hello-blue-whale
#spec:  
#  tls:
#  - hosts:
#      - hello-blue-whale
#    secretName: client-ca
#  rules:
#  - host: hello-blue-whale
#    http:
#      paths:
#      - path: /
#        #pathType: Prefix
#        backend:
#          serviceName: hello-whale-svc
#          servicePort: 8080
          #servicePort: 8081
